# Generated by Django 3.2.3 on 2021-05-22 11:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=32, verbose_name='Plate')),
            ],
        ),
        migrations.CreateModel(
            name='NavigationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('datetime', models.DateTimeField(default=datetime.datetime(2021, 5, 22, 14, 15, 10, 636074), verbose_name='Datetime')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigation.vehicle', verbose_name='Vehicle')),
            ],
        ),
        migrations.AddIndex(
            model_name='navigationrecord',
            index=models.Index(fields=['vehicle', 'datetime'], name='navigation__vehicle_2b7e4f_idx'),
        ),
    ]
